### ISSUE TITLE
Provide a sensible warning if I try to migrate a migrated file

### ISSUE THREAD

**Issue by paulkorir** [emdb-empiar/sfftk-migrate#1]
Currently it spews out some cryptic error. 

```
~$ sff-migrate empiar_10087_c2_tomo02.sff
Traceback (most recent call last):
  File "/Users/pkorir/Envs/sfftk-python3.7/bin/sff-migrate", line 10, in <module>
    sys.exit(main())
  File "/Users/pkorir/Envs/sfftk-python3.7/lib/python3.7/site-packages/sfftk_migrate/main.py", line 83, in main
    status = do_migration(args)
  File "/Users/pkorir/Envs/sfftk-python3.7/lib/python3.7/site-packages/sfftk_migrate/migrate.py", line 113, in do_migration
    shutil.copy(outfile, args.outfile)
  File "/Users/pkorir/Envs/sfftk-python3.7/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/pkorir/Envs/sfftk-python3.7/lib/python3.7/shutil.py", line 103, in copyfile
    if _samefile(src, dst):
  File "/Users/pkorir/Envs/sfftk-python3.7/lib/python3.7/shutil.py", line 88, in _samefile
    return os.path.samefile(src, dst)
  File "/Users/pkorir/Envs/sfftk-python3.7/bin/../lib/python3.7/genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by paulkorir** [comment]
Fixed in 729baeb08d9c934657fa5c243b646ccc881c0220
